export const queryKeys = {
  authStatus: ["auth", "status"] as const,
  me: ["auth", "me"] as const,
  users: ["users"] as const,
  dataStatus: ["data", "status"] as const,
  pipelineJobs: ["pipeline", "jobs"] as const,
  pipelineJob: (id: string) => ["pipeline", "job", id] as const,
  settings: ["settings"] as const,
  preferences: ["settings", "preferences"] as const,
  dataSources: ["settings", "data-sources"] as const,
  capabilityMatrix: ["settings", "capability-matrix"] as const,
  overviewMarket: (asOf?: string) => ["overview", "market", asOf ?? "latest"] as const,
  strategies: ["strategies"] as const,
  strategyOptions: ["strategies", "options"] as const,
  factors: ["factors"] as const,
  factorOptions: ["factors", "options"] as const,
  monitor: ["monitor"] as const,
  klineDaily: (symbol: string) => ["kline", "daily", symbol] as const,
  financialStatus: ["financials", "status"] as const,
  financialMetrics: (symbol: string) => ["financials", "metrics", symbol] as const,
};
